### ISSUE TITLE
Seekr for analysis of netcdf amber20 trajectories

### ISSUE THREAD

**Issue by DDGmichigan** [nbcrrolls/SEEKR#12]
Hello developers,
I was wondering if one wants to use Seekr to analyse the kinetics of binding/unbinding/rebinding to a target receptor; is it possible?
Say I have 10-20 mdcrd  files  of my protein-ligand system and I want to utilize SEEKR to analyze the kinetics of the interactions, is it possible?
Thanks

**Comment by lvotapka** [comment]
Hi,

Yes, SEEKR is designed to allow you estimate the kinetics of binding and unbinding of a molecule to a target receptor. The rebinding kinetics is a little bit trickier, since there is a nonzero probability that the ligand will take infinite time to rebind. However, among the probability of those ligands who rebind in finite time, you would probably be able to estimate the timescales and kinetics of that process. SEEKR doesn't do that automatically, but you could use the resulting statistics from SEEKR to compute that.

Unfortunately, I doubt that you would be able to plug existing trajectories into SEEKR to compute your kinetics without additional simulations. The milestoning procedure is a unique process that requires one to compute the first hitting point distribution with a large number of trajectories prepared and propagated according to a detailed procedure. Though you might be able to "seed" the milestones with your trajectories, you would probably need to run the SEEKR calculation in its entirety to obtain statistics.

If you're interested, you can read about the capabilities and procedure of SEEKR in our paper: https://pubs.acs.org/doi/abs/10.1021/acs.jpcb.6b09388

**Comment by brjagger** [comment]
To add a bit more clarity... Milestoning theory, in general, can be used as a purely post-processing technique for calculating kinetics from a long MD simulation. However this will likely require extremely long simulations in order to have robust binding/unbinding statistics. In practice, you would need to observe multiple binding/unbinding events.

As for SEEKR, it is not currently set up to perform this post-processing type of analysis as it is written to look for specific information in simulation output files that records the milestoning crossing events to calculate the kinetics.

**Comment by DDGmichigan** [comment]
Thanks
I actually have weak binders and I see many multiple binding unbinding events and I wanted to utilize this new software to analyse it further.
Regards
Debarati

**Comment by lvotapka** [comment]
While milestoning theory could certainly be used to analyze your trajectories, SEEKR is not specifically designed to perform that task, unfortunately.
